// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCn699Ku4txFeWcDPAfII9UnfZ7skyXPv8',
    appId: '1:574293582520:android:050ec2f4e7fc8fcbaa8a4d',
    messagingSenderId: '574293582520',
    projectId: 'hackster-38cbf',
    storageBucket: 'hackster-38cbf.appspot.com',
    databaseURL: 'https://hackster-38cbf-default-rtdb.asia-southeast1.firebasedatabase.app',

  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKvTRdv8oy2ki0BxADWNSrEsiRDMsYDfI',
    appId: '1:574293582520:ios:7173d59e511f62fdaa8a4d',
    messagingSenderId: '574293582520',
    projectId: 'hackster-38cbf',
    storageBucket: 'hackster-38cbf.appspot.com',
    iosClientId: '574293582520-840nnvuiot0g7r8ggmbns2lqlbhea5ve.apps.googleusercontent.com',
    iosBundleId: 'com.indesigngraphics.hackster',
    databaseURL: 'https://hackster-38cbf-default-rtdb.asia-southeast1.firebasedatabase.app',
  );
}
