// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbcHOEBTN8vcIY8k94Mun2JW0BMI7bixo',
    appId: '1:185572013929:web:3546943c373bd21ec6aff8',
    messagingSenderId: '185572013929',
    projectId: 'hackster-a8254',
    authDomain: 'hackster-a8254.firebaseapp.com',
    storageBucket: 'hackster-a8254.appspot.com',
    measurementId: 'G-G7CY2MJWYF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARg6UnqeAJ4grdW2_7oM5S1azlku46C5M',
    appId: '1:185572013929:android:1a4b36189c790ee8c6aff8',
    messagingSenderId: '185572013929',
    projectId: 'hackster-a8254',
    storageBucket: 'hackster-a8254.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSISX9wllIzrHygodOgwCsTiWuzL_FEpc',
    appId: '1:185572013929:ios:9f5b6d796f91c4c0c6aff8',
    messagingSenderId: '185572013929',
    projectId: 'hackster-a8254',
    storageBucket: 'hackster-a8254.appspot.com',
    iosClientId: '185572013929-mdbe83cs7ngbasii4f31uus7e1vso53r.apps.googleusercontent.com',
    iosBundleId: 'com.indesigngraphics.hackster',
  );
}
